### ISSUE TITLE
Fix loading a listener cost from a config file

### ISSUE THREAD

**Issue by squidboylan** [ansible/receptor#104]
When specifying a cost in the `cost` or `nodecost` parameter on a listener, if you specify the value without a decimal, for example `1` instead of `1.0`, the config loader fails:

```
squid@localhost:~/work/project-receptor/receptor$ cat foo.yaml
---
- node:
    id: foo
- log-level:
    level: debug
- tcp-listener:
    port: 10000
    cost: 2
- control-service:
    filename: foo.sock
- trace
squid@localhost:~/work/project-receptor/receptor$ ./receptor --config foo.yaml
panic: reflect.Set: value of type int is not assignable to type float64

goroutine 1 [running]:
reflect.Value.assignTo(0x14b8a20, 0xc00028e510, 0x82, 0x16f12d4, 0xb, 0x1495ce0, 0x0, 0x1495ce0, 0x14b8a20, 0x1793500)
        /usr/local/go/src/reflect/value.go:2411 +0x426
reflect.Value.Set(0x1495ce0, 0xc000313568, 0x18e, 0x14b8a20, 0xc00028e510, 0x82)
        /usr/local/go/src/reflect/value.go:1539 +0xbd
github.com/project-receptor/receptor/pkg/cmdline.setValue(0xc0001c77e0, 0x14b8a20, 0xc00028e510, 0xc0001c77e0, 0x0)
        /home/squid/work/project-receptor/receptor/pkg/cmdline/cmdline.go:194 +0xec2
github.com/project-receptor/receptor/pkg/cmdline.loadConfigFromFile(0x7ffd2d0a65b6, 0x8, 0x7ffd2d0a65b6, 0x8, 0xc0001b9dc8, 0x203000, 0x40deb6)
        /home/squid/work/project-receptor/receptor/pkg/cmdline/cmdline.go:448 +0x551
github.com/project-receptor/receptor/pkg/cmdline.ParseAndRun(0xc00011c160, 0x2, 0x2)
        /home/squid/work/project-receptor/receptor/pkg/cmdline/cmdline.go:517 +0x104f
main.main()
        /home/squid/work/project-receptor/receptor/cmd/receptor.go:60 +0x33c
```

**Comment by squidboylan** [comment]
I confirmed this is working manually and will be part of my automated testing for https://github.com/project-receptor/receptor/issues/31
