### ISSUE TITLE
Receptor occassionally panics when a backend disconnects

### ISSUE THREAD

**Issue by squidboylan** [ansible/receptor#207]
I got the following panic when running `TestWork/work_submit_with_incorrect_tlsclient_CN`:

```
panic: send on closed channel

goroutine 50 [running]:
github.com/project-receptor/receptor/pkg/netceptor.(*Netceptor).handleMessageData(0xc0002c0c80, 0xc00032fe00, 0xc0000ebeb0, 0x6)
        /home/squid/work/project-receptor/receptor/pkg/netceptor/netceptor.go:1047 +0x35d
github.com/project-receptor/receptor/pkg/netceptor.(*Netceptor).runProtocol(0xc0002c0c80, 0x19393a0, 0xc0004a2000, 0x3ff0000000000000, 0x0, 0x0, 0x0)
        /home/squid/work/project-receptor/receptor/pkg/netceptor/netceptor.go:1249 +0x19a4
github.com/project-receptor/receptor/pkg/netceptor.(*Netceptor).AddBackend.func1.1(0xc0002c0c80, 0x19393a0, 0xc0004a2000, 0x3ff0000000000000, 0x0)
        /home/squid/work/project-receptor/receptor/pkg/netceptor/netceptor.go:318 +0x5f
created by github.com/project-receptor/receptor/pkg/netceptor.(*Netceptor).AddBackend.func1
        /home/squid/work/project-receptor/receptor/pkg/netceptor/netceptor.go:317 +0xe9
```

This is very rare and seems to be caused by something continuing to use a channel that has been closed because a backend has exited. I'm unsure if this is what caused the test to fail or if this happened when we were shutting down the nodes after the test failed, in either case it seems like a good idea to make note of.

Attached are the logs of the `go test` output with the `-test.v` flag and an archive of the mesh logs, the relevant node is `node1`, this was produced on commit `1396c8d72a697f532957ed353f1a8fea60f67465`. I will look into making a reproducer soon.

[go-test.log.zip](https://github.com/project-receptor/receptor/files/5335319/go-test.log.zip)
[mesh-logs.zip](https://github.com/project-receptor/receptor/files/5335321/mesh-logs.zip)

**Comment by squidboylan** [comment]
I think this was fixed by #208, if it turns out this is still an issue we can reopen this
